jwt:
  expiration: 7200000
upload:
  directory: src/main/resources/uploads/cvs
spring:
  application:
    name: OpportuNet_Hackaton
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/opportunet
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
server:
  port: 8080


